import {analyzeImageFile,runFourAgents,buildProductConsumerSummary,hsvToHex,ANALYSIS_KEYWORDS,circularHueDistance} from './agents.js';
import {createVirtualTryOn} from './tryon.js';

const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const app=$('#app'),toast=$('#toast'),modal=$('#modal-backdrop'),modalContent=$('#modal-content');
let manifest, cache=new Map(), verifyFiles=[], verifyAnalyses=[], selfieFile=null, selfieResult=null;
const PARTS={'ysl-610':4,'ysl-1936':4,'lancome-274':0,'lancome-275':0};
const fmt=n=>new Intl.NumberFormat('zh-CN').format(n||0);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const color=p=>{const c=p.analysis.center;return hsvToHex(c.hue,c.saturation,c.brightness)};
function toastMsg(s){toast.textContent=s;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),1900)}
async function ungzipB64(parts){const txt=(await Promise.all(parts.map(u=>fetch(u).then(r=>{if(!r.ok)throw Error('数据文件未部署完整');return r.text()})))).join('').trim();const bin=Uint8Array.from(atob(txt),c=>c.charCodeAt(0));if(!('DecompressionStream'in window))throw Error('当前浏览器不支持数据解压，请使用最新版 Chrome / Edge / Safari');const stream=new Blob([bin]).stream().pipeThrough(new DecompressionStream('gzip'));return JSON.parse(await new Response(stream).text())}
async function getManifest(){if(manifest)return manifest;manifest=await fetch('./data/manifest.json').then(r=>r.json());return manifest}
function summaryFallback(k){
 const m=manifest.products.find(x=>x.key===k);
 if(!m)throw Error('未找到该色号数据');
 const ids=m.analysis?.topMediaIds||[];
 const media=ids.map((id,i)=>{
   const platform=id.startsWith('xhs-')?'小红书':'淘宝';
   const pm=m.analysis?.platform?.[platform]||m.analysis?.center||{hue:0,saturation:0,brightness:50};
   return {id,platform,type:'离线真实媒体记录',thumb:null,referenceScore:null,
     metrics:{hue:pm.hue,saturation:pm.saturation,brightness:pm.brightness,sceneBrightness:pm.brightness,lighting:'媒体记录',dominant:hsvToHex(pm.hue,pm.saturation,pm.brightness)},
     reasons:['该媒体 ID 来自完整离线数据的 Top reference 排名；公开静态页未重复发布原始高分辨率文件']};
 });
 return {...m,media,reviews:[],asks:[],_summaryOnly:true};
}
async function getProduct(k){
 if(cache.has(k))return cache.get(k);
 const n=PARTS[k]||0;
 if(!n){const p=summaryFallback(k);cache.set(k,p);return p}
 const urls=Array.from({length:n},(_,i)=>`./data/full/${k}.${i+1}.b64`);
 const p=await ungzipB64(urls);cache.set(k,p);return p
}
function meta(k){return manifest.products.find(x=>x.key===k)}
function page(x){app.innerHTML=`<div class="page">${x}</div>`;window.scrollTo(0,0)}
function go(h){location.hash=h}
function shadeCard(p){return `<a class="shade-card" href="#/shade/${p.key}"><div><div class="shade-brand">${esc(p.brand)}</div><div class="shade-code">#${p.shade}</div><div class="shade-name">${esc(p.name)} · ${esc(p.product)}</div><div class="shade-meta"><span class="mini-chip">${p.analysis.counts.visual} 份视觉素材</span><span class="mini-chip">${p.analysis.counts.text} 条文字证据</span><span class="mini-chip">证据充分度 ${p.analysis.evidenceSufficiency}</span></div></div><div class="shade-swatch" style="background:radial-gradient(circle at 38% 35%,${color(p)} 0,#6b352e 48%,#271715 100%)"></div></a>`}
function opts(sel){return manifest.products.map(p=>`<option value="${p.key}" ${p.key===sel?'selected':''}>${esc(p.brand)} #${p.shade} ${esc(p.name)}</option>`).join('')}
function highlight(t){let s=esc(t);for(const k of ANALYSIS_KEYWORDS)s=s.replaceAll(k,`<mark class="highlight">${k}</mark>`);return s}
function reviewCard(r){return `<article class="review"><p>${highlight(r.text)}</p><small><span>${r.platform}</span><span>${r.type||'评论'}</span>${r.sku?`<span>${esc(r.sku)}</span>`:''}${r.repeatBuyer?'<span>复购线索</span>':''}${r.negativeEvidence?'<span>含负向体验</span>':''}</small></article>`}
function mediaCard(m,i){const score=Number.isFinite(m.referenceScore)?Math.round(m.referenceScore)+'/100':'Top reference';return `<article class="media-card" data-media="${m.id}">${m.thumb?`<img src="${m.thumb}" alt="真实试色参考图 ${i+1}">`:'<div class="skeleton media-placeholder" style="height:210px"><span>真实媒体记录<br><small>原图未在公开静态页重发</small></span></div>'}<div class="media-card-body"><div class="rank">#${i+1} · ${score}</div><div class="source-line">${m.platform} · ${m.metrics?.lighting||m.type}</div><div class="reason">${esc((m.reasons||[])[0]||'接近多来源参考色域')}</div></div></article>`}
function metric(label,v,max=100,u='%'){return `<div class="metric-row"><label>${label}</label><div class="bar"><i style="width:${Math.min(100,Math.abs(v)/max*100)}%"></i></div><span>${Number(v).toFixed(1)}${u}</span></div>`}
function evidenceScoreText(a){return `视觉 ${a.counts.images} 图 + ${a.counts.videos} 视频元数据 · 文字 ${fmt(a.counts.text)} 条 · ${a.counts.sources} 类来源`}

async function home(){
 await getManifest(); page(`
 <section class="hero"><div><div class="eyebrow">Beauty × AI × Trust</div><h1>看见的颜色，<br>真的是你买到的颜色吗？</h1><p>TrueTone 把散落在小红书与电商里的试色、评论和色差线索整理成真正能用的购买参考。不是替你下结论，而是告诉你：<strong style="color:#f1dcd1;font-weight:500">哪些内容更值得看，以及为什么。</strong></p><div class="home-search"><div class="searchbox"><span class="search-icon">⌕</span><input id="q" placeholder="搜索品牌或色号，例如 610 / 274"></div><button class="primary-btn" id="qgo">查看真实试色</button></div></div><aside class="hero-side"><strong>先从你的购买问题出发。</strong>想知道一个色号在自己脸上可能怎么呈现？想核验一张种草图？还是已经有目标色号？技术证据都放在结论之后，需要时再展开。</aside></section>
 <section class="entry-grid">
 <a class="entry-card" href="#/tryon"><div class="entry-num">01</div><h3>看看它在我脸上</h3><p>上传自拍，用 TrueTone 参考色域做局部虚拟试色，并找到与你当前光照和使用情况更接近的真实参考。</p><div class="entry-cta">上传自拍 →</div></a>
 <a class="entry-card" href="#/verify"><div class="entry-num">02</div><h3>这张试色值得信吗？</h3><p>上传 1–多张图片，真实计算光照、饱和度、亮度、色相和跨图一致性，给出可解释的参考可信度。</p><div class="entry-cta">核验试色 →</div></a>
 <a class="entry-card" href="#/search"><div class="entry-num">03</div><h3>直接查一个色号</h3><p>先看 Top 3 真实试色，再看相似唇色消费者反馈、跨平台差异和购买前提醒。</p><div class="entry-cta">搜索色号 →</div></a></section>
 <section class="section"><div class="section-head"><div><div class="eyebrow">试试示例</div><h2>从真实数据开始</h2></div><p>4 个色号的已爬取样本已结构化导入；YSL #610 与 Lancôme #274 是主 Demo。</p></div><div class="shade-grid">${manifest.products.map(shadeCard).join('')}</div></section>
 <section class="privacy-strip"><strong>自拍隐私：</strong>当前公开版在浏览器本地处理，不上传、不保存、不加入产品数据集；不进行年龄、种族、身份、健康或颜值判断。</section>`);
 $('#qgo').onclick=()=>quick($('#q').value);$('#q').onkeydown=e=>e.key==='Enter'&&quick(e.target.value)
}
function quick(q){q=(q||'').toLowerCase().replace('#','').trim();const p=manifest.products.find(x=>x.shade===q||x.brand.toLowerCase().includes(q)||x.name.toLowerCase().includes(q));p?go('/shade/'+p.key):go('/search')}

async function search(){
 await getManifest();page(`<div class="route-head"><a class="backlink" href="#/">← 首页</a><div class="eyebrow" style="margin-top:22px">搜索已有色号</div><h1>先找一个你正在纠结的颜色</h1><p>先看最值得参考的真实试色和与你情况更接近的反馈，再决定要不要买。</p></div><div class="searchbox" style="max-width:720px"><span class="search-icon">⌕</span><input id="catalog-q" placeholder="YSL / Lancôme / 610 / 274…"></div><div class="shade-grid" id="catalog" style="margin-top:18px">${manifest.products.map(shadeCard).join('')}</div>`);
 $('#catalog-q').oninput=e=>{$('#catalog').innerHTML=manifest.products.filter(p=>(p.brand+p.name+p.product+p.shade).toLowerCase().includes(e.target.value.toLowerCase())).map(shadeCard).join('')||'<div class="empty">当前 Demo 数据库里暂时没有这个色号。</div>'}
}

async function shade(k){
 const m=meta(k);
 if(!m)return home();
 page(`<div class="route-head"><a class="backlink" href="#/search">← 返回色号库</a><div class="eyebrow" style="margin-top:22px">${esc(m.brand)} · ${esc(m.product)}</div><h1>#${m.shade} ${esc(m.name)}</h1><p>先从消费者的购买问题出发。点击分析后，TrueTone 才会读取当前色号的证据集，并依次运行颜色/环境、风险审查、消费者报告与创作者建议四个模块。</p></div>
 <section class="analysis-start">
  <div class="panel analysis-intro">
   <div class="eyebrow">本次分析证据集</div>
   <h2>不是先给你一个分数，而是先看证据。</h2>
   <div class="source-counts"><span><b>${m.analysis.counts.visual}</b> 份视觉素材</span><span><b>${fmt(m.analysis.counts.text)}</b> 条文字证据</span><span><b>${m.analysis.counts.sources}</b> 类来源</span><span><b>${m.analysis.counts.skus}</b> 个 SKU / 产品线标签</span></div>
   ${m.skuLines?.length>1?`<div class="sku-warning">同一色号包含多个 SKU / 产品线：${m.skuLines.map(esc).join('、')}。系统会保留这些边界，避免把产品差异误判成内容失真。</div>`:''}
   <div class="plain-note" style="margin-top:14px">真实性评分与证据充分度是两个不同概念；“正面评价”也不会直接被当成“真实”。</div>
  </div>
  <div class="panel">
   <div class="eyebrow">TrueTone 4-Agent Flow</div>
   <div class="agent-steps" id="product-agent-steps">
    <div class="agent-step" data-a="1">Agent 1 · 色彩 / ROI / 光照</div>
    <div class="agent-step" data-a="2">Agent 2 · 风险 / 跨图一致性 / 评分</div>
    <div class="agent-step" data-a="3">Agent 3 · 消费者报告 / Top 3 / 评论证据</div>
    <div class="agent-step" data-a="4">Agent 4 · 内容改进 / 可解释建议</div>
   </div>
   <button class="primary-btn" id="start-product-analysis" style="width:100%;margin-top:16px">开始 TrueTone 分析</button>
   <div class="progress" style="margin-top:12px"><i id="product-progress"></i></div>
  </div>
 </section>`);
 $('#start-product-analysis').onclick=async()=>{
   const btn=$('#start-product-analysis'),steps=$$('#product-agent-steps .agent-step'),bar=$('#product-progress');
   btn.disabled=true;btn.textContent='正在读取证据集…';
   try{
     await getProduct(k);
     const labels=['正在分析颜色与拍摄环境…','正在交叉核验风险与一致性…','正在整理消费者最有用的证据…','正在生成改进建议…'];
     for(let i=0;i<steps.length;i++){
       steps.forEach((s,j)=>{if(j<i)s.className='agent-step done';else if(j===i)s.className='agent-step active';else s.className='agent-step'});
       btn.textContent=labels[i];bar.style.width=((i+1)/steps.length*100)+'%';await wait(i===0?360:260);
     }
     steps.forEach(s=>s.className='agent-step done');
     await shadeReport(k);
   }catch(e){
     btn.disabled=false;btn.textContent='重新尝试';
     toastMsg('数据读取失败：'+e.message);
   }
 }
}

async function shadeReport(k){
 const p=await getProduct(k),a=p.analysis,c=buildProductConsumerSummary(p),top=c.top,sku=p.skuLines||[];
 page(`<div class="route-head"><a class="backlink" href="#/search">← 返回色号库</a><div class="eyebrow" style="margin-top:22px">${esc(p.brand)} · ${esc(p.product)}</div><h1>#${p.shade} ${esc(p.name)}</h1><p>先给购买结论，再展开依据。下面的分数、排序和统计来自当前真实 sample data 与可复现分析逻辑，不是写死的展示数字。</p>${sku.length>1?`<div class="sku-warning">SKU 提醒：当前样本同一色号包含 <b>${sku.length}</b> 个产品线 / SKU：${sku.map(esc).join('、')}。系统保留 SKU 边界，不把不同产品本身的差异误判成“P 图”。</div>`:''}</div>
 <section class="report-hero"><div class="panel"><div class="eyebrow">一句话结论</div><div class="conclusion">${esc(c.conclusion)}</div><div class="source-counts"><span><b>${a.counts.visual}</b> 份视觉素材</span><span><b>${fmt(a.counts.text)}</b> 条文字证据</span><span><b>${a.counts.sources}</b> 类来源</span></div><div class="filter-row" style="margin-top:18px"><span style="font-size:11px;color:var(--muted);align-self:center">更像你的情况：</span><button class="filter-btn active" data-prof="all">全部</button><button class="filter-btn" data-prof="深唇">深唇</button><button class="filter-btn" data-prof="浅唇">浅唇</button><button class="filter-btn" data-prof="素颜">素颜</button></div></div>
 <div class="panel score-panel"><div class="score-ring" style="--score:${a.score};--ring:${a.score>=80?'#82b996':a.score>=60?'#e2b16b':'#d46d60'}"><b>${a.score}</b></div><div class="score-label"><strong>TrueTone 参考可信度</strong>它不是“真假裁决”，而是当前内容适不适合作为购买参考。<span class="evidence-badge">证据充分度：${a.evidenceSufficiency}</span><div class="disclaimer">${evidenceScoreText(a)}。真实性评分与证据充分度分开。</div></div></div></section>
 <section class="panel report-section" id="top-ref"><div class="section-head"><div><div class="eyebrow">Top 3 reference</div><h2 style="font-size:28px">你最值得先看的 3 张</h2></div><p>按 reference score 排序：曝光、饱和、色温、与多来源中心色的接近程度共同影响。</p></div><div class="top-media" id="top-media">${top.map(mediaCard).join('')}</div></section>
 <section class="details-grid"><div class="panel"><h3>消费者色差证据</h3><div class="keyword-cloud">${Object.entries(a.keywordCounts).sort((x,y)=>y[1]-x[1]).slice(0,18).map(([x,n])=>`<span class="kw">${x} <b>${n}</b></span>`).join('')}</div><div class="plain-note" style="margin-top:15px">${a.consumerDifferenceMentions} 条文本提到偏色、色差或“和图片不一样”等线索。评论质量层还识别到：复购/回头客 ${a.reviewQuality.repeatBuyer} 条；负向体验 ${a.reviewQuality.negativeEvidence} 条；模板化泛评 ${a.reviewQuality.genericTemplate} 条会降低权重。</div></div><div class="panel"><h3>与你情况相关的真实反馈</h3><div class="review-list" id="reviews">${c.reviews.slice(0,7).map(reviewCard).join('')}</div></div></section>
 <section class="details-grid"><div class="panel"><h3>TrueTone 参考色域</h3><div class="swatches">${p.media.filter(m=>m.metrics?.dominant).sort((x,y)=>(y.referenceScore||0)-(x.referenceScore||0)).slice(0,14).map(m=>`<span class="swatch-dot" style="background:${m.metrics.dominant}" title="${m.platform} · score ${m.referenceScore}"></span>`).join('')}</div><div class="plain-note" style="margin-top:13px">中心：H ${a.center.hue}° · S ${a.center.saturation}% · B ${a.center.brightness}%。这是多来源样本形成的参考色域，不是“绝对真实色”。</div></div><div class="panel"><h3>小红书 vs 淘宝</h3>${metric('色相差异',a.platformDiff.hue,90,'°')}${metric('饱和度差异',Math.abs(a.platformDiff.saturation),35,'%')}${metric('亮度差异',Math.abs(a.platformDiff.brightness),35,'%')}<div class="plain-note">小红书 H${a.platform['小红书'].hue} / S${a.platform['小红书'].saturation} / B${a.platform['小红书'].brightness}<br>淘宝 H${a.platform['淘宝'].hue} / S${a.platform['淘宝'].saturation} / B${a.platform['淘宝'].brightness}</div></div></section>
 <section class="details-grid"><div class="panel"><h3>为什么是这个分数？</h3>${(a.findings||[]).length?(a.findings||[]).map(f=>`<div class="finding"><span class="severity ${f.severity}">${f.severity==='high'?'高风险':f.severity==='medium'?'中风险':'低风险'}</span><div><strong>${esc(f.type)}</strong><p>在 ${f.count||1} 个样本中触发；根据项目既定扣分规则影响总分。</p></div></div>`).join(''):'<div class="plain-note">当前产品级汇总没有触发 high / medium 异常扣分；总分仍不等于“绝对真实”。</div>'}<div class="plain-note" style="margin-top:12px">评分保留原方案：base 82；单图 high −4 / medium −2 / low −1；跨图 high −8 / medium −4；范围 25–95。</div></div><div class="panel"><h3>哪些差异属于正常变化？</h3><div class="review-list">${c.normal.map(x=>`<div class="review"><p>${esc(x)}</p></div>`).join('')||'<div class="plain-note">当前文本证据不足以细分更多正常变化。</div>'}</div></div></section>
 <section class="cta-band"><div><h3>想知道 #${p.shade} 在你脸上可能怎么呈现？</h3><p>上传自拍后，TrueTone 会优先从真实样本里找更接近你当前光照和使用情况的参考图与评论。</p></div><a class="primary-btn" href="#/tryon?p=${p.key}">上传自拍</a></section>
 <section class="cta-band"><div><h3>喜欢这个方向吗？</h3><p>不喜欢也没关系，可以换成更橘、更浅或不同质地，再看相似色号。</p></div><div style="display:flex;gap:8px;flex-wrap:wrap"><button class="secondary-btn" id="like">喜欢，看看相似色</button><button class="ghost-btn" id="warmer">想更橘一点</button><a class="ghost-btn" href="#/compare">我在纠结两个色号</a></div></section>`);
 $$('.filter-btn[data-prof]').forEach(b=>b.onclick=()=>{ $$('.filter-btn[data-prof]').forEach(x=>x.classList.remove('active'));b.classList.add('active');const prof=b.dataset.prof;const cc=buildProductConsumerSummary(p,prof);$('#reviews').innerHTML=cc.reviews.slice(0,7).map(reviewCard).join('')||'<div class="plain-note">当前数据中没有足够匹配评论。</div>'});
 $$('.media-card[data-media]').forEach(x=>x.onclick=()=>openMedia(p,x.dataset.media));
 $('#like').onclick=()=>recommend(p,false);$('#warmer').onclick=()=>recommend(p,true);
}
function recommend(p,warm){const candidates=manifest.products.filter(x=>x.key!==p.key).map(x=>({p:x,d:circularHueDistance(p.analysis.center.hue,x.analysis.center.hue)+(warm?(x.analysis.center.hue<p.analysis.center.hue?18:0):0)})).sort((a,b)=>a.d-b.d).slice(0,3);modalContent.innerHTML=`<div class="eyebrow">Similar shades</div><h2 id="modal-title">${warm?'更偏暖 / 橘一点的方向':'相似色号'}</h2><p>只在当前欧莱雅集团 Demo 数据内推荐，依据参考色域距离与质地方向，不伪装成全市场推荐。</p><div class="shade-grid">${candidates.map(x=>shadeCard(x.p)).join('')}</div>`;openModal()}
function openMedia(p,id){const m=p.media.find(x=>x.id===id);if(!m)return;modalContent.innerHTML=`<div class="eyebrow">${m.platform} · 单图证据</div><h2 id="modal-title">Reference score ${Math.round(m.referenceScore||0)}/100</h2>${m.thumb?`<img src="${m.thumb}" style="width:100%;max-height:520px;object-fit:contain;background:#090807;border-radius:14px">`:''}<div class="details-grid" style="margin-top:15px"><div class="panel"><h3>像素指标</h3><p>Hue ${m.metrics?.hue??'—'}°<br>Saturation ${m.metrics?.saturation??'—'}%<br>Brightness ${m.metrics?.brightness??'—'}%<br>光照：${m.metrics?.lighting||'—'}</p></div><div class="panel"><h3>推荐 / 降权原因</h3><p>${esc((m.reasons||[]).join('；')||'当前样本未记录额外说明')}</p></div></div>`;openModal()}

async function verify(){
 await getManifest();page(`<div class="route-head"><a class="backlink" href="#/">← 首页</a><div class="eyebrow" style="margin-top:22px">上传试色核验</div><h1>这张试色，值得你参考吗？</h1><p>图片只在当前浏览器中读取像素。可一次上传多张；多图会自动做跨图一致性比较与推荐排序。</p></div><section class="upload-shell"><label class="dropzone" id="drop"><input id="verify-input" type="file" accept="image/png,image/jpeg,image/webp" multiple hidden><div><div class="upload-icon">＋</div><h3>拖进来，或点这里选择图片</h3><p>JPG / PNG / WEBP · 支持多张 · 可删除、追加</p></div></label><div class="file-previews" id="previews"></div><div class="form-row"><select class="select" id="source"><option>小红书</option><option>淘宝/电商</option><option>用户实拍</option><option>其他</option></select><select class="select" id="match-product"><option value="">不与已有色号比较</option>${opts('')}</select><button class="primary-btn" id="run-verify" disabled>开始 TrueTone 分析</button></div><div class="progress"><i id="vprogress"></i></div><div class="agent-run hidden" id="agent-run"><div class="agent-steps"><div class="agent-step" data-a="1">Agent 1 · 色彩/光照</div><div class="agent-step" data-a="2">Agent 2 · 鉴伪/一致性</div><div class="agent-step" data-a="3">Agent 3 · 消费者报告</div><div class="agent-step" data-a="4">Agent 4 · 改进建议</div></div></div></section><div id="verify-results"></div>`);
 const input=$('#verify-input'),drop=$('#drop');drop.ondragover=e=>{e.preventDefault();drop.classList.add('drag')};drop.ondragleave=()=>drop.classList.remove('drag');drop.ondrop=e=>{e.preventDefault();drop.classList.remove('drag');addVerify([...e.dataTransfer.files])};input.onchange=()=>addVerify([...input.files]);$('#run-verify').onclick=runVerify
}
function addVerify(fs){verifyFiles.push(...fs.filter(f=>f.type.startsWith('image/')));renderVerifyPreviews()}
function renderVerifyPreviews(){const el=$('#previews');el.innerHTML=verifyFiles.map((f,i)=>`<div class="preview-card"><button class="remove-file" data-i="${i}">×</button><img src="${URL.createObjectURL(f)}"><div class="meta">${esc(f.name)}</div></div>`).join('');$$('.remove-file').forEach(b=>b.onclick=e=>{e.preventDefault();verifyFiles.splice(+b.dataset.i,1);renderVerifyPreviews()});$('#run-verify').disabled=!verifyFiles.length}
async function runVerify(){const btn=$('#run-verify');btn.disabled=true;verifyAnalyses=[];$('#agent-run').classList.remove('hidden');const steps=$$('.agent-step');steps.forEach(x=>x.className='agent-step');steps[0].classList.add('active');for(let i=0;i<verifyFiles.length;i++){verifyAnalyses.push(await analyzeImageFile(verifyFiles[i]));$('#vprogress').style.width=((i+1)/verifyFiles.length*55)+'%'}steps[0].className='agent-step done';steps[1].className='agent-step active';let p=null;if($('#match-product').value)p=await getProduct($('#match-product').value);await wait(220);const report=runFourAgents(verifyAnalyses,p);steps[1].className='agent-step done';steps[2].className='agent-step active';await wait(180);steps[2].className='agent-step done';steps[3].className='agent-step active';await wait(150);steps[3].className='agent-step done';$('#vprogress').style.width='100%';renderVerifyResults(report);btn.disabled=false;btn.textContent='重新分析'}
function renderVerifyResults(r){const ranked=verifyAnalyses.map((x,i)=>({x,i,score:Math.max(25,95-(x.metrics.saturation>75?8:0)-(x.metrics.sceneBrightness>80?8:0)-(x.metrics.sceneBrightness<30?4:0)-((x.metrics.lighting==='暖光'||x.metrics.lighting==='冷光')?4:0))})).sort((a,b)=>b.score-a.score);$('#verify-results').innerHTML=`<section class="report-hero"><div class="panel"><div class="eyebrow">分析完成</div><div class="conclusion">${esc(r.summary)}</div><div class="plain-note">分析置信度：${r.confidence}% · 输入 ${verifyAnalyses.length} 张图片</div></div><div class="panel score-panel"><div class="score-ring" style="--score:${r.score}"><b>${r.score}</b></div><div class="score-label"><strong>参考可信度</strong>来自真实像素指标与项目原评分规则。</div></div></section><section class="panel report-section"><h3>最值得参考的上传图片</h3><div class="top-media">${ranked.slice(0,3).map((q,n)=>`<article class="media-card"><img src="${q.x.views.original}"><div class="media-card-body"><div class="rank">#${n+1} · ${q.score}/100</div><div class="source-line">${q.x.metrics.lighting}</div><div class="reason">H ${q.x.metrics.hue}° · S ${q.x.metrics.saturation}% · B ${q.x.metrics.brightness}%</div></div></article>`).join('')}</div></section><section class="panel report-section"><h3>视觉证据墙 · 5 种真实像素视图</h3><div class="filter-row" id="diag-tabs">${verifyAnalyses.map((x,i)=>`<button class="filter-btn ${i?'':'active'}" data-img="${i}">图 ${i+1}</button>`).join('')}</div><div id="diag"></div></section><section class="details-grid"><div class="panel"><h3>为什么是这个分数？</h3>${r.findings.map(f=>`<div class="finding"><span class="severity ${f.severity}">${f.severity}</span><div><strong>${esc(f.type)}</strong><p>${esc(f.evidence)} · ${esc(f.impact)}</p></div></div>`).join('')||'<div class="plain-note">未触发明显视觉风险；仍不代表“绝对真实”。</div>'}</div><div class="panel"><h3>给内容创作者的改进建议</h3>${r.suggestions.map(s=>`<div class="review"><p><b>${esc(s.title)}</b><br>${esc(s.why)}<br><span style="color:var(--gold)">预期改善：</span>${esc(s.impact)}</p></div>`).join('')}</div></section>`;$$('#diag-tabs .filter-btn').forEach(b=>b.onclick=()=>showDiag(+b.dataset.img));showDiag(0)}
function showDiag(i){const x=verifyAnalyses[i];$$('#diag-tabs .filter-btn').forEach((b,n)=>b.classList.toggle('active',n===i));$('#diag').innerHTML=`<div class="diagnostic-tabs"><button class="tab-btn active" data-v="original">原图</button><button class="tab-btn" data-v="roi">试色候选区</button><button class="tab-btn" data-v="saturation">饱和度</button><button class="tab-btn" data-v="brightness">亮度</button><button class="tab-btn" data-v="composite">综合</button></div><div class="diag-view"><img id="diag-img" src="${x.views.original}"></div><div class="plain-note" style="margin-top:10px">H ${x.metrics.hue}° · S ${x.metrics.saturation}% · B ${x.metrics.brightness}% · ${x.metrics.lighting} · 候选色区 ${x.metrics.candidateRatio}%</div>`;$$('[data-v]').forEach(b=>b.onclick=()=>{$$('[data-v]').forEach(z=>z.classList.remove('active'));b.classList.add('active');$('#diag-img').src=x.views[b.dataset.v]})}

async function tryon(){
 await getManifest();const param=new URLSearchParams((location.hash.split('?')[1]||''));const preset=param.get('p')||'ysl-610';page(`<div class="route-head"><a class="backlink" href="#/">← 首页</a><div class="eyebrow" style="margin-top:22px">自拍个性化试色</div><h1>别问“它适不适合所有人”。<br>先看它在这张自拍里可能怎么呈现。</h1><p>只分析当前照片中的颜色、光照与唇部位置；不推断种族、年龄、身份、健康或颜值。</p></div><section class="tryon-layout"><label class="photo-stage" id="selfie-stage"><input id="selfie-input" type="file" accept="image/png,image/jpeg,image/webp" hidden><div class="empty-stage" id="selfie-empty"><div class="upload-icon">＋</div><h3>上传自然光、无滤镜、嘴唇清晰的正脸自拍</h3><p>自拍仅用于本次浏览器内分析，不上传。</p></div><img id="selfie-img" class="hidden"><div class="toggle hidden" id="try-toggle" style="position:absolute;left:14px;bottom:14px"><button class="active" data-show="tryon">虚拟试色</button><button data-show="original">原自拍</button></div></label><aside class="panel try-controls"><div><div class="eyebrow">Step 1</div><h3>选择色号</h3><div class="choice-grid" id="try-products">${manifest.products.map(p=>`<button class="choice ${p.key===preset?'active':''}" data-p="${p.key}"><b>#${p.shade}</b><br><small>${esc(p.brand)} · ${esc(p.name)}</small></button>`).join('')}</div></div><div><div class="eyebrow">Step 2 · 可选</div><h3>告诉我们你的使用情况</h3><div class="form-row"><select class="select" id="lip-prof"><option value="all">唇色：不确定</option><option>浅唇</option><option>深唇</option></select><select class="select" id="tone-prof"><option value="auto">冷暖：按照片</option><option value="warm">偏暖</option><option value="neutral">中性</option><option value="cool">偏冷</option></select></div><button class="primary-btn" id="run-try" disabled>分析当前自拍</button><label style="display:flex;gap:7px;margin-top:11px;color:var(--muted);font-size:11px"><input id="debug" type="checkbox"> 调试模式：显示唇部 landmarks / polygon</label></div><div class="quality-list" id="quality"></div></aside></section><div id="try-results"></div>`);
 const input=$('#selfie-input'),stage=$('#selfie-stage');stage.onclick=e=>{if(e.target.closest('.toggle'))return;input.click()};input.onchange=()=>{selfieFile=input.files[0];if(!selfieFile)return;const u=URL.createObjectURL(selfieFile);$('#selfie-img').src=u;$('#selfie-img').classList.remove('hidden');$('#selfie-empty').classList.add('hidden');$('#run-try').disabled=false};$$('#try-products .choice').forEach(b=>b.onclick=e=>{e.preventDefault();$$('#try-products .choice').forEach(x=>x.classList.remove('active'));b.classList.add('active')});$('#run-try').onclick=runTry
}
async function runTry(){if(!selfieFile)return;const btn=$('#run-try');btn.disabled=true;btn.textContent='正在识别唇部…';const p=await getProduct($('#try-products .active').dataset.p);try{selfieResult=await createVirtualTryOn(selfieFile,p,$('#debug').checked);$('#selfie-img').src=selfieResult.tryon;$('#try-toggle').classList.remove('hidden');$$('#try-toggle button').forEach(b=>b.onclick=e=>{e.preventDefault();$$('#try-toggle button').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#selfie-img').src=selfieResult[b.dataset.show]});$('#quality').innerHTML=selfieResult.quality.map(x=>`<div class="quality"><span>${esc(x.label)}</span><b>${esc(x.value)}</b></div>`).join('');renderTryResult(p)}catch(e){$('#quality').innerHTML=`<div class="sku-warning">${esc(e.message)}</div>`}finally{btn.disabled=false;btn.textContent='重新分析'}}
function renderTryResult(p){const r=selfieResult,a=p.analysis,lip=$('#lip-prof').value,tone=$('#tone-prof').value;let reviews=p.reviews.filter(x=>a.representativeReviewIds.includes(x.id));if(lip!=='all'){const t=reviews.filter(x=>x.text.includes(lip));if(t.length)reviews=t}if(tone==='warm'){const t=reviews.filter(x=>/黄皮|暖调|偏暖/.test(x.text));if(t.length)reviews=t}if(tone==='cool'){const t=reviews.filter(x=>/冷白|冷调|偏冷/.test(x.text));if(t.length)reviews=t}reviews=reviews.slice(0,3);const top=p.media.filter(m=>m.thumb&&m.metrics).map(m=>({...m,personal:(m.referenceScore||0)-(m.metrics.lighting===r.light.label?0:7)-Math.abs((m.metrics.sceneBrightness||60)-r.light.brightness)*.18})).sort((x,y)=>y.personal-x.personal).slice(0,3);const c=a.center,expected={h:c.hue,s:Math.max(5,c.saturation+(r.faceRef.saturation-30)*.08),b:Math.max(5,Math.min(95,c.brightness+(r.light.brightness-60)*.12))};$('#try-results').innerHTML=`<section class="details-grid"><div class="panel"><div class="eyebrow">当前自拍质量</div><h3>当前照片颜色参考</h3><div style="display:flex;gap:14px;align-items:center"><span class="swatch-dot" style="width:58px;height:58px;background:${r.faceRef.hex}"></span><div class="plain-note">${r.faceRef.tone}<br>${r.faceRef.hex} · 明度 ${r.faceRef.brightness}% · 饱和度 ${r.faceRef.saturation}%<br><small>仅代表当前照片。</small></div></div></div><div class="panel"><div class="eyebrow">预计呈现</div><h3>#${p.shade} 在当前自拍中可能怎么呈现？</h3><div class="plain-note">当前为 <b style="color:#fff">${r.light.label}</b>。结合多来源参考色域，预计呈现 H ${expected.h.toFixed(1)}° · S ${expected.s.toFixed(1)}% · B ${expected.b.toFixed(1)}%。</div><div class="swatches" style="margin-top:12px"><span class="swatch-dot" title="TrueTone 参考中心" style="background:${hsvToHex(c.hue,c.saturation,c.brightness)}"></span><span class="swatch-dot" title="当前自拍预计" style="background:${hsvToHex(expected.h,expected.s,expected.b)}"></span></div><div class="disclaimer">虚拟试色为视觉模拟，仅供参考，不代表实物最终效果。</div></div></section><section class="panel report-section"><div class="section-head"><div><div class="eyebrow">Personal reference</div><h2 style="font-size:28px">最值得你参考的 3 张真实试色</h2></div><p>同时考虑原 reference score、与你当前光照/亮度的接近程度。</p></div><div class="top-media">${top.map((m,i)=>`<article class="media-card"><img src="${m.thumb}"><div class="media-card-body"><div class="rank">#${i+1} · ${Math.round(m.personal)}/100</div><div class="source-line">${m.platform} · ${m.metrics.lighting}</div><div class="reason">${esc((m.reasons||[])[0]||'接近参考色域')}</div></div></article>`).join('')}</div></section><section class="panel report-section"><div class="section-head"><div><div class="eyebrow">Matched comments</div><h2 style="font-size:28px">最匹配的 3 条消费者反馈</h2></div></div><div class="review-list">${reviews.map(reviewCard).join('')||'<div class="plain-note">当前没有足够匹配文本。</div>'}</div></section><section class="cta-band"><div><h3>下一步：回到完整色号报告</h3><p>把自拍预览、真实 Top 3、消费者反馈和 SKU 信息放在一起做购买判断。</p></div><a class="secondary-btn" href="#/shade/${p.key}">查看 #${p.shade} 报告</a></section>`}

async function compare(){
 await getManifest();page(`<div class="route-head"><a class="backlink" href="#/">← 首页</a><div class="eyebrow" style="margin-top:22px">色号对比</div><h1>纠结两个颜色？放在同一把尺子上。</h1><p>比较多来源参考色域、证据充分度与消费者反馈，而不只比较官方商品图。</p></div><div class="compare-pickers"><div class="compare-col"><select id="ca" class="select" style="width:100%">${opts('ysl-610')}</select></div><div class="compare-col"><select id="cb" class="select" style="width:100%">${opts('lancome-274')}</select></div></div><div id="cmp"></div>`);$('#ca').onchange=renderCmp;$('#cb').onchange=renderCmp;renderCmp()
}
async function renderCmp(){const [a,b]=await Promise.all([getProduct($('#ca').value),getProduct($('#cb').value)]);const cp=p=>`<div class="shade-brand">${esc(p.brand)}</div><div class="shade-code">#${p.shade}</div><div class="shade-name">${esc(p.name)} · ${esc(p.texture)}</div><div class="shade-swatch" style="height:130px;margin:18px 0;background:radial-gradient(circle at 40% 35%,${color(p)},#61342e 55%,#251515 100%)"></div><div class="compare-stat"><div class="stat"><b>${p.analysis.score}</b><span>参考可信度</span></div><div class="stat"><b>${p.analysis.evidenceSufficiency}</b><span>证据充分度</span></div><div class="stat"><b>${p.analysis.center.saturation}%</b><span>饱和度</span></div><div class="stat"><b>${p.analysis.center.brightness}%</b><span>明度</span></div></div><a class="secondary-btn" style="margin-top:14px" href="#/shade/${p.key}">看完整报告</a>`;$('#cmp').innerHTML=`<div class="comparison"><div class="panel">${cp(a)}</div><div class="panel">${cp(b)}</div></div><section class="panel report-section"><h3>一眼看懂差异</h3><div class="plain-note">参考色域中心的环形色相距离约 <b style="color:#fff">${circularHueDistance(a.analysis.center.hue,b.analysis.center.hue).toFixed(1)}°</b>；饱和度差 ${Math.abs(a.analysis.center.saturation-b.analysis.center.saturation).toFixed(1)}%，明度差 ${Math.abs(a.analysis.center.brightness-b.analysis.center.brightness).toFixed(1)}%。</div></section>`}

function openAbout(){modalContent.innerHTML=`<div class="eyebrow">How it works</div><h2 id="modal-title">TrueTone 不是一个“真假按钮”</h2><p>当前公开版保留项目原有四个 Agent 的职责：先做真实像素与环境分析，再按固定规则审查风险，再把证据翻译成消费者报告，最后给内容改进建议。</p><div class="method-flow"><div><b>Agent 1</b>HSV / 光照 / ROI 候选区 / 真实像素诊断</div><div><b>Agent 2</b>异常 / 跨图一致性 / 0–100 评分</div><div><b>Agent 3</b>一句话结论 / Top 3 / 评论证据</div><div><b>Agent 4</b>拍摄与创作者改进建议</div></div><p>现有产品报告使用已结构化导入的小红书 + 淘宝 sample data；169 张 JPG 已离线做真实像素统计，29 个视频保留来源与媒体元数据。自拍使用 MediaPipe Face Mesh 的唇部 landmarks → outer polygon − inner mouth mask，避免把牙齿和口腔涂色。</p><p><b style="color:#fff">关于“真实 Agent”：</b>这里的四 Agent 是会实际运行的确定性分析模块，不是随机 UI。公开 GitHub Pages 不安全地存放任何大模型 API Key；后续接入 Base44 安全后端时，可以让 LLM 只做语言整合，评分与证据仍由可复现逻辑提供。</p>`;openModal()}
function openModal(){modal.hidden=false;document.body.style.overflow='hidden'}function closeModal(){modal.hidden=true;document.body.style.overflow=''}function wait(ms){return new Promise(r=>setTimeout(r,ms))}
async function router(){try{await getManifest();const p=(location.hash.slice(1)||'/').split('?')[0];if(p==='/'||p==='/home')return home();if(p==='/search')return search();if(p.startsWith('/shade/'))return shade(p.split('/')[2]);if(p==='/verify')return verify();if(p==='/tryon')return tryon();if(p==='/compare')return compare();return home()}catch(e){console.error(e);page(`<div class="route-head"><h1>数据加载失败</h1><p>${esc(e.message)}</p><a class="secondary-btn" href="#/">返回首页</a></div>`)}}
$('#open-method').onclick=openAbout;$('#modal-close').onclick=closeModal;modal.onclick=e=>e.target===modal&&closeModal();document.addEventListener('keydown',e=>e.key==='Escape'&&closeModal());window.addEventListener('hashchange',router);router();
