import {analyzeVisualForensics} from './visual-forensics.js?v=20261007-acceptance-v12';
import {forensicHtml,bindGenerationChecks} from './forensic-ui.js?v=20261007-acceptance-v12';
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));let sequence=0;
async function check(file,context='用户上传图片，处理历史未知。'){
 const seq=++sequence;$('#forensic-result').innerHTML='<p>正在进行源图匹配和局部变化检测…</p>';const report=await analyzeVisualForensics(file);if(seq!==sequence)return;const original=URL.createObjectURL(file);$('#forensic-result').innerHTML=`<p class="scope-note">${esc(context)}</p><img class="forensic-original" src="${original}" alt="本次检查图片">${forensicHtml([report])}`;$('#forensic-result img').onload=()=>URL.revokeObjectURL(original);bindGenerationChecks($('#forensic-result'),[file]);
}
try{
 const bench=await fetch('./data/forensics/benchmark.json').then(r=>r.json());const examples=[['control','未施加新增编辑的对照'],['local_color_strong','局部改色'],['splice','局部拼接'],['ai_generated','已知 AI 生成样本']];
 for(const [kind,label] of examples){const row=bench.records.find(r=>r.phase==='test'&&r.kind===kind),button=document.createElement('button');button.className='secondary-btn';button.textContent=label;button.dataset.fixture=kind;button.onclick=async()=>{const request=++sequence;$('#forensic-result').textContent='正在读取并检查测试图片…';try{const response=await fetch('./data/forensics/'+row.image);if(!response.ok)throw Error();const blob=await response.blob();if(request!==sequence)return;await check(new File([blob],row.id+'.png',{type:'image/png'}),'受控示例：'+label+'。检测不读取此操作标签；AI 生成图没有可比源图，请继续运行生成模型。')}catch{$('#forensic-result').textContent='测试图片未加载，请稍后重试。'}};$('#fixture-buttons').append(button)}
 $('#forensic-upload').onchange=()=>{if($('#forensic-upload').files[0])check($('#forensic-upload').files[0])};
 const result=await fetch('./data/forensics/test-summary.json').then(r=>{if(!r.ok)throw Error();return r.json()});
 $('#benchmark-summary').innerHTML=`<h2>冻结阈值后的测试结果</h2><div class="forensic-stats"><article><b>${result.reference.negativesFalsePositive}/${result.reference.negatives}</b><p>正常处理对照的误报</p></article><article><b>${result.reference.positivesDetected}/${result.reference.positives}</b><p>新增局部编辑被检出</p></article><article><b>${result.generation.generatedDetected}/${result.generation.generated}</b><p>已知生成图触发模型阈值</p></article></div><p>12 个调参原帖与 12 个测试原帖隔离。局部检测有可比源图作为输入；不是没有源图的盲测。6 张生成测试图来自同一次生成，不能视作 6 个独立生成来源。</p><table><thead><tr><th>测试操作</th><th>检出 / 数量</th><th>平均定位 IoU</th></tr></thead><tbody>${result.byKind.filter(r=>r.positive).map(r=>`<tr><td>${esc(r.label)}</td><td>${r.detected}/${r.count}</td><td>${r.meanIoU.toFixed(2)}</td></tr>`).join('')}</tbody></table><p>没有相近源图时，局部检测保留“无法核验”。生成模型也会误报或漏检；完整失败样本公开在测试报告中。</p>`;
}catch{$('#benchmark-summary').innerHTML='<h2>测试记录暂未加载</h2><p>未完成的测量不会显示为准确率，请稍后重试。</p>'}
