import {hsvToRgb,hsvToHex,rgbToHsv} from './agents.js';
let faceMesh=null;
const OUTER=[61,185,40,39,37,0,267,269,270,409,291,375,321,405,314,17,84,181,91,146];
const INNER=[78,191,80,81,82,13,312,311,310,415,308,324,318,402,317,14,87,178,88,95];
function loadImage(file){return new Promise((resolve,reject)=>{const img=new Image();const u=URL.createObjectURL(file);img.onload=()=>{URL.revokeObjectURL(u);resolve(img)};img.onerror=reject;img.src=u})}
function initFaceMesh(){if(faceMesh)return faceMesh;if(!window.FaceMesh)throw new Error('Face Mesh 未加载');faceMesh=new window.FaceMesh({locateFile:f=>`https://cdn.jsdelivr.net/npm/@mediapipe/face_mesh/${f}`});faceMesh.setOptions({maxNumFaces:2,refineLandmarks:true,minDetectionConfidence:.55,minTrackingConfidence:.5});return faceMesh}
function detect(img){return new Promise(async(resolve,reject)=>{try{const fm=initFaceMesh();fm.onResults(r=>resolve(r));await fm.send({image:img})}catch(e){reject(e)}})}
function polygon(ctx,pts,w,h){pts.forEach((id,i)=>{const p=window.__lm[id];const x=p.x*w,y=p.y*h;if(i===0)ctx.moveTo(x,y);else ctx.lineTo(x,y)});ctx.closePath()}
function avgAround(data,w,h,points,r=8){let sr=0,sg=0,sb=0,n=0;for(const p of points){const cx=Math.round(p.x*w),cy=Math.round(p.y*h);for(let y=Math.max(0,cy-r);y<Math.min(h,cy+r);y++)for(let x=Math.max(0,cx-r);x<Math.min(w,cx+r);x++){const i=(y*w+x)*4;sr+=data[i];sg+=data[i+1];sb+=data[i+2];n++}}return n?[Math.round(sr/n),Math.round(sg/n),Math.round(sb/n)]:[0,0,0]}
function classifyLight(data){let r=0,g=0,b=0,v=0,n=data.length/4;for(let i=0;i<data.length;i+=4){r+=data[i];g+=data[i+1];b+=data[i+2];v+=(Math.max(data[i],data[i+1],data[i+2])/255*100)}r/=n;g/=n;b/=n;v/=n;let label='中性光';if(v>82)label='过曝';else if(v<28)label='偏暗';else if(r-b>18)label='暖光';else if(r-b<-12)label='冷光';return {label,brightness:+v.toFixed(1),warm:+(r-b).toFixed(1)}}
function applyLipColor(base,mask,target){const ctx=base.getContext('2d',{willReadFrequently:true}),img=ctx.getImageData(0,0,base.width,base.height),m=mask.getContext('2d').getImageData(0,0,base.width,base.height).data;const d=img.data;for(let i=0;i<d.length;i+=4){if(m[i+3]<80)continue;const [h,s,v]=rgbToHsv(d[i],d[i+1],d[i+2]);const ns=s+(target.saturation-s)*.84;const nv=Math.max(8,Math.min(98,v+(target.brightness-v)*.26));const [r,g,b]=hsvToRgb(target.hue,ns,nv);const a=.82*(m[i+3]/255);d[i]=d[i]*(1-a)+r*a;d[i+1]=d[i+1]*(1-a)+g*a;d[i+2]=d[i+2]*(1-a)+b*a}ctx.putImageData(img,0,0);return base}
export async function createVirtualTryOn(file,product,debug=false){const img=await loadImage(file);const scale=Math.min(1,900/Math.max(img.naturalWidth,img.naturalHeight));const w=Math.round(img.naturalWidth*scale),h=Math.round(img.naturalHeight*scale);const original=document.createElement('canvas');original.width=w;original.height=h;original.getContext('2d').drawImage(img,0,0,w,h);const imageData=original.getContext('2d').getImageData(0,0,w,h);const light=classifyLight(imageData.data);const res=await detect(img);if(!res.multiFaceLandmarks||!res.multiFaceLandmarks.length)throw new Error('未能稳定识别唇部，请上传正脸、光线充足、嘴唇无遮挡的自拍。');const faces=res.multiFaceLandmarks;const area=f=>{const xs=f.map(p=>p.x),ys=f.map(p=>p.y);return (Math.max(...xs)-Math.min(...xs))*(Math.max(...ys)-Math.min(...ys))};faces.sort((a,b)=>area(b)-area(a));window.__lm=faces[0];const lm=window.__lm;
 const rawMask=document.createElement('canvas');rawMask.width=w;rawMask.height=h;const mc=rawMask.getContext('2d');mc.fillStyle='#fff';mc.beginPath();polygon(mc,OUTER,w,h);polygon(mc,INNER,w,h);mc.fill('evenodd');
 const mask=document.createElement('canvas');mask.width=w;mask.height=h;const fc=mask.getContext('2d');const blurPx=Math.max(1,Math.min(3,Math.round(Math.max(w,h)/500)));fc.filter=`blur(${blurPx}px)`;fc.drawImage(rawMask,0,0);fc.filter='none';
 const out=document.createElement('canvas');out.width=w;out.height=h;out.getContext('2d').drawImage(original,0,0);const target=product.tryOnColor||product.analysis.center;applyLipColor(out,mask,target);
 if(debug){const oc=out.getContext('2d');oc.strokeStyle='#ffd7ad';oc.lineWidth=2;oc.beginPath();polygon(oc,OUTER,w,h);polygon(oc,INNER,w,h);oc.stroke();oc.fillStyle='#fff';for(const id of OUTER.concat(INNER)){const p=lm[id];oc.beginPath();oc.arc(p.x*w,p.y*h,2.2,0,Math.PI*2);oc.fill()}}
 const cheeks=[lm[50],lm[280]];const [r,g,b]=avgAround(imageData.data,w,h,cheeks,10);const [hh,ss,vv]=rgbToHsv(r,g,b);const faceRef={hex:'#'+[r,g,b].map(x=>x.toString(16).padStart(2,'0')).join(''),brightness:+vv.toFixed(1),saturation:+ss.toFixed(1),tone:(r-b>12?'中性偏暖':(r-b<-8?'中性偏冷':'中性'))};
 const quality=[];quality.push({label:'人脸/唇部',value:'识别稳定'});if(faces.length>1)quality.push({label:'多人画面',value:'已默认选择面积最大的人脸'});quality.push({label:'当前光照',value:light.label});quality.push({label:'画面亮度',value:`${light.brightness}%`});if(light.label==='过曝'||light.label==='偏暗'||light.label==='暖光'||light.label==='冷光')quality.push({label:'提示',value:'光照可能影响预计呈现'});
 return {original:original.toDataURL('image/jpeg',.9),tryon:out.toDataURL('image/jpeg',.9),mask:mask.toDataURL('image/png'),quality,light,faceRef,target:{...target,hex:hsvToHex(target.hue,target.saturation,target.brightness)}}
}
